services:
  postgres:
    image: postgres:latest
    container_name: projexbio-postgres
    env_file:
      - .env
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
